### ISSUE TITLE
[SECONDARY FEATURE]  Progress Bar & Timeline

### ISSUE THREAD

**Issue by MarcCruzs** [BroncoDirectMe/Website#10]
### User Story
As a website user, I should be able to see the progress of the project so that I can be able to keep track of what was finished and still needs to be done.

### Technical Task:
Use CSS or React to make progress bar

### Acceptance Criteria:
- Progress bar depicting a concise illustration of project progress

**Comment by misslame** [comment]
includes investigating.

**Comment by GuyWhoCode** [comment]
Closed as this issue is no longer needed.
