### ISSUE TITLE
[TECH-DEBT] Script that runs multiple npm install commands 

### ISSUE THREAD

**Issue by misslame** [BroncoDirectMe/Website#25]
¯\_(ツ)_/¯
 
 Needs a way to delete package.json and rerun 1 command that installs all the needed dependencies.

**Comment by Carbrex** [comment]
Will a bash script do?

**Comment by Carbrex** [comment]
> Will a bash script do?

?

**Comment by misslame** [comment]
Idk who you are, this is a closed student project.
