### ISSUE TITLE
[SECONDARY FEATURE] Nav Bar

### ISSUE THREAD

**Issue by misslame** [BroncoDirectMe/Website#3]
### User Story
As a user, I should be able to click buttons that link to different pages so that I can navigate between different subject matter pages such as documentation, landing page, credits page, and current project progress page. 

### Technical Task:
Use CSS or React to make a nav bar

### Acceptance Criteria:
- Nav bar that allows for clicking between pages

**Comment by InsightCracker** [comment]
I can actually do that both css and react.

Assigned it to me nd see the wonderful navbar on your website

**Comment by U-k-t** [comment]
@codeboyfriend Sorry, this is a project that's being kept in-house to provide some current undergrads from our alma mater the opportunity to experience work in an agile development environment and develop their technical capabilities. We appreciate the offer but are going to have to respectfully decline.

**Comment by Samanyu24X** [comment]
Added an MUI stack of buttons with hrefs to create navbar, and added routing in App.tsx

**Comment by misslame** [comment]
@Samanyu24X  You can not close issues until they have been merged to Dev
