### ISSUE TITLE
[DOCUMENTATION] Update Preview videos

### ISSUE THREAD

**Issue by GuyWhoCode** [BroncoDirectMe/Website#54]
On the home page, the videos need to be updated to match the new UI.

**Comment by Asish-AP** [comment]
@GuyWhoCode can you elaborate if the videos are to be added in the website home page or the readme. 
Because its showing documentation

**Comment by wheatleyinabox** [comment]
Look into Video Indexing Report
Link: https://support.google.com/webmasters/answer/9495631#indexing_status
